### ISSUE TITLE
'str' object has no attribute 'decode' while exiting b0RemoteApi

### ISSUE THREAD

**Issue by olek130** [CoppeliaRobotics/b0RemoteApiBindings#1]
Such error occured when I tried to use the Bluezero remote API for a new project. 

In CoppeliaSim scene I have b0RemoteApiServer dummy copied from synchronousImageTransmissionViaRemoteApi.ttt . I've got the same error while trying to launch synchronousImageTransmission.py example script with this environment. 

Environment: Python 3.7 (Conda virtual env)

```
Traceback (most recent call last):
  File "MyPath\VrepConnection.py", line 15, in __del__
    self.client.__exit__()
  File "MyPath\B0_Vrep_Api\b0RemoteApi.py", line 49, in __exit__
    self.simxSpinOnce();
  File "MyPath\B0_Vrep_Api\b0RemoteApi.py", line 179, in simxSpinOnce
    self._handleReceivedMessage(readData)
  File "MyPath\b0RemoteApi.py", line 63, in _handleReceivedMessage
    msg[0]=msg[0].decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

My code:
```
from b0RemoteApi import RemoteApiClient

class VrepConnection :
	def __init__( self, nodeName: str, channel: str) :
		print("[INFO] Initializing VrepConnection object")
		self.nodeName = nodeName
		self.channel = channel
		self.client = RemoteApiClient( self.nodeName, self.channel, 60 )

	def __del__(self):
		print("[INFO] Deleting VrepConnection object")
		self.client.__exit__()
		
```

**Comment by olek130** [comment]
I found that the problem might be that the string is already decoded at this point. I've made simple check in b0RemoteApi.py and it worked for this case. Not sure if this will be a problem later. 
```
try:
	msg[ 0 ] = msg[ 0 ].decode( 'ascii' )
except AttributeError :
	pass
```

**Comment by Coppelia** [comment]
Hello Aleksander,
you are right, the new msgpack version (1.0.0 vs 0.5.6) breaks something. You can either check the "Pack strings as binary" on the CoppeliaSim side, or modify "b0RemoteApi.py" on line 62 to:
msg=msgpack.unpackb(msg,raw=True)
and on line 73 to:
rep = msgpack.unpackb(self._serviceClient.call(packedData),raw=True)

Thanks again
